name: End-to-end tests
on:
  push:
    branches-ignore:
      - '**'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn test:e2e
          wait-on: 'http://localhost:3000'
        env:
          stage: LOCAL
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
